name: CI

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build development image
      uses: docker/build-push-action@v5
      with:
        context: .
        target: development
        tags: nab-bank-api:dev
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run linting
      run: |
        docker run --rm -v $(pwd):/app nab-bank-api:dev golangci-lint run --timeout=5m --issues-exit-code=1

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build development image
      uses: docker/build-push-action@v5
      with:
        context: .
        target: development
        tags: nab-bank-api:dev
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run tests with coverage
      run: |
        docker run --rm -v $(pwd):/app nab-bank-api:dev go test -race -coverprofile=coverage.out -covermode=atomic ./...

    - name: Generate coverage report
      run: |
        docker run --rm -v $(pwd):/app nab-bank-api:dev go tool cover -html=coverage.out -o coverage.html

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.out
        flags: unittests
        name: codecov-umbrella

  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build development image
      uses: docker/build-push-action@v5
      with:
        context: .
        target: development
        tags: nab-bank-api:dev
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run security scan
      run: |
        docker run --rm -v $(pwd):/app nab-bank-api:dev sh -c "go install github.com/securecodewarrior/gosec/v2/cmd/gosec@latest && gosec ./..."

  build:
    runs-on: ubuntu-latest
    needs: [lint, test, security]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build production image
      uses: docker/build-push-action@v5
      with:
        context: .
        target: production
        tags: nab-bank-api:latest
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test production image
      run: |
        # Start the container in the background
        docker run -d --name test-container -p 8080:8080 \
          -e NAB_USERNAME=test \
          -e NAB_PASSWORD=test \
          -e NAB_BASE_URL=https://test.com \
          nab-bank-api:latest
        
        # Wait for the service to start
        sleep 10
        
        # Test health endpoint
        curl -f http://localhost:8080/health || exit 1
        
        # Clean up
        docker stop test-container
        docker rm test-container